### PR TITLE
evoload.py with backup url

### PR DESCRIPTION
**Pull request by kasi45**

### CODE REVIEW

**Comment by kasi45** [comment]
<edit: _Remove Infringing site_>

this "Filmpalast" url uses the backup url from 'evoload'.

**Comment by Gujal00** [comment]
@kasi45 
I have done it differently in https://github.com/jsergio123/script.module.resolveurl/commit/7b0e2aa84b20d82461b0e2299e7559b2e2e60fdd
See if that works for you

**Comment by kasi45** [comment]
@Gujal00 

```

r = json.loads(shtml).get('stream')
status = 0
surl = r.get('backup')
try:
    status = self.net.http_GET(surl)._response.code
except:
    pass
surl = r.get('backup') if status == 200 else r.get('src')
if surl:
    headers.pop('X-XSRF-TOKEN')
    return surl + helpers.append_headers(headers)


```

You find the string of the URL (bachkup) but the stream from this URL is dead. 
Only with a status check the second URL would be used

**Comment by Gujal00** [comment]
@kasi45 no if backup is present that has the correct url with md5, the code works correctly as I tested with multiple embeds including the one you gave

**Comment by kasi45** [comment]
@Gujal00 
Hello and good day,
there is a misunderstanding here because I am not very good at expressing myself in the English language

of course they determine both strings (backup / src) completely correctly. If the string (backup) is not present, then the correct string (src) is also processed.
This makes is their Python code much more elegant than my old code.

Let's assume the following situation:
There is the string (backup) and there is the string (scr) in 'shtml'.

In this case the string (backup) is passed on.

A video addon, which wants to have the resolved string from 'evoload', uses this string (backup) as URL/link and wants to have the stream from this URL.
Now it can be that this link is dead.

If we further assume that the string (src) would have had a valid link, then the video addon can no longer switch to that link (src) at that time.
Only the 'resolveURL' would have been able to do this before.

That's why I added a check for the first string (backup). It is checked if the URL can be resolved from the string. (StatusCode 200)
If this check is not successful, then already in 'resolveURL' is changed to second string and this second string (src) is passed to the video addon.

I hope that I have now expressed myself more clearly.

**Comment by Gujal00** [comment]
@kasi45
testing stream availability is more involved than what you have shown there
1. You need to add headers including cookies, etc as otherwise you could get 403 for a valid stream
2. Doing a http_GET will pull the whole file if it is present and that is no good unless it is m3u8 which are quite small
3. ResolveURL uses six library for handling PY2/PY3 differences, so it will be using urllib_error from six.moves instead of a try/except for urllib.error and urllib2

The actual function for testing stream already exists in hmf.py `__test_stream` and you can see how involved it is,
Still I haven't hit an embed where backup is present but not working. Will keep an eye out to find one and then code accordingly

You can discuss [more here](https://keybase.io/team/resolveurl)

**Comment by kasi45** [comment]
@Gujal00 

Thank you for your comments and explanations.
So I could learn and understand something again.
It was important to me to give a suggestion.
However, I still lack the basics for a detailed discussion. Acquiring the basics is something I will work on over time.

Many thanks for their efforts

**Comment by Gujal00** [comment]
@kasi45 suggestions are always welcome, English is not my first language either, so please don't feel discouraged discussing solutions.
Worst case sceanario I add a function to helpers.py, it already has a get_redirect_url, just need to tweak that a bit to get the response code. I feel that it is currently unnecessary for this resolver but if we run into any embeds that behave differently, then yes it could be done

**Pull request closed without merging**
