### PR TITLE
Videomega Resolver

### PR DESCRIPTION
**Pull request by kingul**

### CODE REVIEW

**Comment by jsergio123** [comment]
the generic resolver can handle this site

**Comment by kingul** [comment]
That means that all p a c k e d resolvers could be handled by generic resolver?
Couldn't find any jsunpack in resolvegeneric

**Comment by jsergio123** [comment]
Yes as long as the regex needed matches the generic patterns. The generic resolver calls upon helpers.get_media_url() which calls upon helpers.scrape_sources() which handles packed data. See here https://github.com/jsergio123/script.module.resolveurl/blob/84f4d19c2d5ddf35e7149891a1282d23314c8c7b/lib/resolveurl/plugins/lib/helpers.py#L155

You could also call helpers.scrape_sources() directly and set your own regex/patterns and it will search for and unpack any packed data found.

See here https://github.com/jsergio123/script.module.resolveurl/blob/7339c1d7821a0c78c7df3c6c71b453d73fd6183a/lib/resolveurl/plugins/vidorg.py#L35

**Comment by kingul** [comment]
Ok!

**Comment by jsergio123** [comment]
I can help better directly on keybase

**Pull request closed without merging**
