### PR TITLE
New Resolver - Fix imports

### PR DESCRIPTION
**Pull request by lukkie112**
I have closed my PullRequest #253 and open an new one with Import fix from 
host505, Thanks to for showing my bugs

### CODE REVIEW

**Review by Gujal00 — COMMENTED** [review]
@lukkie112 First of, Thank you for the great effort.

However, 
1. Please raise one PR per resolver, this way it is easy to merge one if everything is fine with it 
2. All three resolvers can be done using the Generic resolver
3. In case of Supervideo, there are multiple qualities available and your pattern only matches the first one. Please have a look on how to match multiple qualities in my PR

I have done three individual PRs #264 #265 #266 using Generic Resolver for the hosters you coded for. Please review on how simple it is to do with Generic resolver in most cases. Only in certain cases you may have to write the code the way you have done

**Comment by Gujal00** [comment]
@jsergio123 
Please do not merge this PR as I have raised PRs for the three hosters in this PR.

**Comment by jsergio123** [comment]
Thanks @Gujal00

**Comment by lukkie112** [comment]
Thanks for Information. Nex Time I will do it.Greets

**Pull request closed without merging**
