### PR TITLE
Update addon.xml

### PR DESCRIPTION
**Pull request by stalitsa2000**

### CODE REVIEW

**Comment by Gujal00** [comment]
what is it that you are trying to fix here?

**Comment by stalitsa2000** [comment]
Am trying to fix icdrama addon for kodi matrix .. but  I can’t

**Comment by Gujal00** [comment]
So why are to trying to change addon.xml of ResolveURL, it works fine in both Kodi 18 and 19.
There are so many addon that use ResolveURL successfully in both Kodi 18 and 19. No problems here

**Comment by stalitsa2000** [comment]
I saw it on site .. All having the same problem with me

**Pull request closed without merging**
