### PR TITLE
Import script.module.requests; Update vidtodo.py;

### PR DESCRIPTION
**Pull request by doko-desuka**
requests.Session() is my bro

### CODE REVIEW

**Comment by jsergio123** [comment]
@doko-desuka please remove the sessions import. Thank you

**Comment by doko-desuka** [comment]
Hi. Requests is a Python library available in Kodi through the official add-ons (meaning, with that single line of import on addon.xml it'll always be available).

It's more robust and failproof than t0mm0's Net module being used.
The Session class handles cookies automatically, which would help reduce a few lines of your plugins that are already handling that.

I've successfully used it on several scrapers and add-ons.
If this is non-negotiable then please close this and I'll keep my own fork.

**Comment by jsergio123** [comment]
The Net module is simple and lightweight. I am open to importing Requests but just not at this time. I would have to migrate all the other plugins over to Requests first and remove the Net module. 

If you like I can make the changes to your PR using the Net module.

**Comment by doko-desuka** [comment]
That script works by the way, even with all the other Net-based plugins. So if that's a concern, you don't have to migrate everything to Requests first.  
You can have some Requests-based and some Net-based plugins running at the same time.

But anyway, it's your call. I'll update it to use the Net module.

**Pull request closed without merging**
