### PR TITLE
fix gounlimited

### PR DESCRIPTION
**Pull request by anis3**
kodi18 & kodi19A1 ok

### CODE REVIEW

**Comment by Gujal00** [comment]
@anis3 as I mentioned earlier in #369 , the changes you are doing is no different to what the Generic Resolver already does, can you please test with v5.1.10 and if still not working, please share the embed url. I have tried with a lot of embed urls and they all work

**Comment by anis3** [comment]
not playing

**Comment by anis3** [comment]
Problem is send Referer
answer : "Video embed restricted for this domain gounlimited.to"

**Comment by Gujal00** [comment]
Thanks for the embeds, It is a very minor addition to the code still using Generic resolver
Fixed in https://github.com/jsergio123/script.module.resolveurl/commit/adec3b92905b21b8e24bde133b455767a1414b60
Please test and confirm. I will close this PR without merging.

**Comment by anis3** [comment]
TNX work

**Pull request closed without merging**
