### PR TITLE
Updated supported video extensions for debrid transfers

### PR DESCRIPTION
**Pull request by host505**
@Gujal00 
1. I see in the current list some audio files extensions (.aac, .ogg, .m4a, .mka). Is there a reason for this?
2. Current supported extensions list as reported by `xbmc.getSupportedMedia('video')` on Kodi 19.3 is:
```
['.m4v', '.3g2', '.3gp', '.nsv', '.tp', '.ts', '.ty', '.strm', '.pls', '.rm', '.rmvb', '.mpd', '.m3u', '.m3u8', '.ifo', '.mov', '.qt', '.divx', '.xvid', '.bivx',
'.vob', '.nrg', '.img', '.iso', '.udf', '.pva', '.wmv', '.asf', '.asx', '.ogm', '.m2v', '.avi', '.bin', '.dat', '.mpg', '.mpeg', '.mp4', '.mkv', '.mk3d',
'.avc', '.vp3', '.svq3', '.nuv', '.viv', '.dv', '.fli', '.flv', '.001', '.wpl', '.xspf', '.zip', '.vdr', '.dvr-ms', '.xsp', '.mts', '.m2t', '.m2ts', '.evo', '.ogv',
'.sdp', '.avs', '.rec', '.url', '.pxml', '.vc1', '.h264', '.rcv', '.rss', '.mpls', '.mpl', '.webm', '.bdmv', '.bdm', '.wtv', '.trp', '.f4v', '.pvr', '.disc',
'.7z', '.tar.gz', '.tar.bz2', '.tar.xz', '.zip', '.tgz', '.tbz2', '.gz', '.bz2', '.xz', '.tar']
```
I excluded
`['.url', '.bin', '.zip', '.rar', '.001', '.disc', '.7z', '.tar.gz', '.tar.bz2', '.tar.xz', '.tgz', '.tbz2', '.gz', '.bz2', '.xz', '.tar']`
Please advice/review.

### CODE REVIEW

**Comment by Gujal00** [comment]
Any reason you are excluding disc images such as .bin and .disc, The other image formats in the list are .nrg .img .iso .udf ?

**Comment by host505** [comment]
I've never seen .bin image files used for videos. But probably that's true for other extensions in the list. So what do you suggest, keep them all?

**Comment by Gujal00** [comment]
Yeah I think we can keep the disc image formats and just exclude the compressed archive formats

**Comment by Gujal00** [comment]
Thanks

**Pull request merged**
