### PR TITLE
Fix Tusfiles

### PR DESCRIPTION
**Pull request by shellc0de27**

### CODE REVIEW

**Comment by Gujal00** [comment]
Did you test any embeds with this? I dont think it will work with generic resolver

**Comment by shellc0de27** [comment]
Based off of the urls im currently returning, it works. Couple media_ids to test: ckt9dmejvirm and 25r4w9zxnuv9

**Comment by shellc0de27** [comment]
Unless this is like a couple of the others I've worked on, where it would be download only. But i haven't came across any as of yet

**Comment by Gujal00** [comment]
okay i was testing with kvj3fgytkji4 which is download only
I have redone the plugin and pushed. Please test if it works fine and if so I will close this PR without merging

**Comment by shellc0de27** [comment]
Perfect, tested. So it seems maybe mkv files are different and not watchable on their player. Which means we should code it for the download. Thanks.

**Pull request closed without merging**
