### PR TITLE
Update vidwatch.py

### PR DESCRIPTION
**Pull request by Gujal00**
Add new domain

### CODE REVIEW

**Comment by rrosajp** [comment]
hi gujal00
i think it's still not working

`DEBUG: ResolveURL: in valid_url http://vidwatch.me/embed-z05f1opr3r9v.html : vidwatch.me (ENCODED)
2019-08-06 13:54:35.070 T:3488   DEBUG: ResolveURL: Using method cache for: |resolveurl.plugins.zevera.ZeveraResolver.get_all_hosters|(<resolveurl.plugins.zevera.ZeveraResolver object at 0x0FCA3BB0>,)|{}| -> |6|
2019-08-06 13:54:35.070 T:3488   DEBUG: ResolveURL: Resolving using vidwatch.me plugin
2019-08-06 13:54:35.576 T:3488   DEBUG: ResolveURL: []
2019-08-06 13:54:35.577 T:3488   ERROR: ResolveURL: ResolverError Error - From: vidwatch.me Link: http://vidwatch.me/embed-z05f1opr3r9v.html: No Video Link Found
2019-08-06 13:54:35.577 T:3488   DEBUG: ResolveURL: Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 186, in resolve
                                                stream_url = resolver.get_media_url(self._host, self._media_id)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\plugins\__resolve_generic__.py", line 49, in get_media_url
                                                return helpers.get_media_url(self.get_url(host, media_id)).replace(' ', '%20')
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\plugins\lib\helpers.py", line 196, in get_media_url
                                                source = pick_source(source_list)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\plugins\lib\helpers.py", line 71, in pick_source
                                                raise ResolverError(common.i18n('no_video_link'))
                                            ResolverError: No Video Link Found`

can u pl help .

**Comment by Gujal00** [comment]
@rrosajp Please test with this updated one

**Comment by rrosajp** [comment]
@Gujal00 
thanks it work on this url
[http://vidwatch.me/embed-19fyjmyil02z.html](url)
but it did not resolving this url
[http://vidwatch3.me/embed-19fyjmyil02z.html](url)

hear is the log if u need.
[https://throwbin.io/7P7Gwk3](url)

**Comment by Gujal00** [comment]
@rrosajp Please test with this updated one. the issue was vidwatch3.me was taken over by some domain parking ad provider.

**Comment by rrosajp** [comment]
@Gujal00 
oh i c
thanks for all help
can u pl look in to this resolver
vkprime
[http://vkprime.com/embed-3jvvvolhkwo8.html](url)

**Comment by Gujal00** [comment]
@rrosajp 
dont mix issues for other resolvers inside a PR. Raise a new issue

**Pull request merged**
