### PR TITLE
🔥 Fix Avideo 🔥 

### PR DESCRIPTION
**Pull request by shellc0de27**
😏

### CODE REVIEW

**Comment by Gujal00** [comment]
Why is it on fire? 😆 
Thanks

**Comment by shellc0de27** [comment]
Lmao hot fix

**Comment by soter80** [comment]
This fix colud resolve  the problem with streamlare?

**Comment by Gujal00** [comment]
@soter80 why do you think this fix will resolve streamlare an unrelated hoster for this avideo plugin?

Edit: Ah, I see for some reason this PR is referenced in the streamlare issue. No idea why github thinks I mentioned that issue under this PR.

**Comment by soter80** [comment]
> @soter80 why do you think this fix will resolve streamlare an unrelated hoster for this avideo plugin?
> 
> Edit: Ah, I see for some reason this PR is referenced in the streamlare issue. No idea why github thinks I mentioned that issue under this PR.

Yes because in issue was referenced this pull request

**Comment by shellc0de27** [comment]
It's due to the fire 🤣🤣🤪

**Pull request merged**
