### PR TITLE
updated vidtodo resolver

### PR DESCRIPTION
**Pull request by jewbmx**
Fixed by doko a while back

### CODE REVIEW

**Comment by jewbmx** [comment]
I havent played with it yet but vidup is now .io for a domain, also streamplay if i recall correctly is behind craptcha right now so broken.

**Comment by jewbmx** [comment]
Made a resolver for idtbox and it looks like it got added to this pr when i uploaded it. Might need some TLC but its been tested by a few people and is working.

**Comment by lukkie112** [comment]
Maybe, If its possible, could you please add verystream to Hoster List?

**Comment by jewbmx** [comment]
Lol 2 posts in a hour about the same resolver and neither have a sample url or helpful info. You can try this but dont know if it works

https://gist.githubusercontent.com/jewbmx/1696dbab653751334095455efe9425ed/raw/ad91b259cbc4b0b588a3757ee1029c0f69d49815/verystream.py

**Comment by jewbmx** [comment]
Yea i give up on trying to edit that post lol. I will toss the links back in this one tho incase someone bothers with this more.
`https://verystream.com/api#download-getlink
https://verystream.com/stream/Y2KCxdbFAJg/sel_v_xinto_s2_wsc_19_e.mp4
`

**Comment by jewbmx** [comment]
I found that timewatch.video also has some sources for that verystream host but havent got it to work so think someone smarter is gonna have to make it lol

**Comment by lukkie112** [comment]
oh, OK. Thanks for Testing

**Review by jsergio123 — CHANGES_REQUESTED** [review]

**Review by jsergio123 — CHANGES_REQUESTED** [review]
please add GNU license

**Comment by jsergio123** [comment]
@lukkie112 verystream created https://github.com/jsergio123/script.module.resolveurl/commit/f1c890cd636b9a536b82be208b372300eeafb8ca

**Comment by jewbmx** [comment]
Im not sure if i did what ya wanted lol kinda guessed, both resolvers are working for me and your new verystreams working good too.

**Comment by jsergio123** [comment]
@jewbmx hey reach out to me here https://keybase.io/team/resolveurl

**Comment by jewbmx** [comment]
Sent ya a msg sir.

**Pull request closed without merging**
