### PR TITLE
Update captcha_lib

### PR DESCRIPTION
**Pull request by frankiek3**
Changes:
- Enhanced get_response with configurable image layout
- Moved io.write into write_img to allow external use
- Closed io.write using 'with' block
- Removed unnecessary file remove
- Added CCapImg captcha support
- Implemented write_img in do_solvemedia_captcha and do_ccapimg_captcha

### CODE REVIEW

**Comment by frankiek3** [comment]
Use case:
-Needed ccapimg captcha support
-Image blocked by keyboard prompt, needed y position to be around 225

**Comment by frankiek3** [comment]
Typo from autocorrect in commit comment, io not up

**Comment by frankiek3** [comment]
FYI: with-as requires python 2.5
https://www.python.org/dev/peps/pep-0343/

**Comment by Gujal00** [comment]
Thanks @frankiek3 for this, this is one library that I couldn't test when I converted ResolveURL to be Matrix compatible. Looking at the code now, it looks like it could fail in Kodi 19 due to usage of `.decode('base64')`. Can you please let me know if your changes work on both Kodi 18 and 19

**Comment by frankiek3** [comment]
I'm on Kodi 18.8, I'll see if I can test on Kodi 19

I referenced io.open in the commit, that was my mistake.
FYI: In python 2 io.open is functionally the same as the built-in open in how I used it in the captcha_lib. In python 3 they are the same.

**Comment by Gujal00** [comment]
Thanks!

**Comment by frankiek3** [comment]
I'm sorry, I didn't mean to give the impression that it was done being tested.

Python 2 and 3:
I'm still testing, and found at least one issue and fixed it in this commit: 13f475878228f3c7eb58e1e82cd094b333a217af

Python 3:
In https://github.com/jsergio123/script.module.resolveurl/blob/master/lib/resolveurl/lib/net.py on line 376:
common.Net will fail on a download that the content-type is unknown and that contains bytes over 127 like `\xaa`
`'ascii'` can be changed to `'iso-8859-1'`, but I haven't checked if it is compatible with the rest of resolveurl encodings.

**Pull request merged**
