### PR TITLE
Update onlystream.py

### PR DESCRIPTION
**Pull request by Gujal00**
Fix resolver

### CODE REVIEW

**Comment by bjgood** [comment]
This one is not working for me. At least on the episodes I have tried.

**Comment by jsergio123** [comment]
@bjgood provide a link, use hxxp:// please.

**Comment by Gujal00** [comment]
yeah provide a link please. Also onlystream.tv is the real embedder, onlystream.xyz is not an embedder and their links wont work with this resolver.

**Comment by bjgood** [comment]
Hey JSergio and Gujal00,
I use a RPi3 to run Kodi (the latest version). After a scan of an episode (actually multiple series and episodes), and onlystream shows up, but when selected it is quickly skipped over time and again, how am I to provide a link?

Sorry I couldn't be more help.

If onlystream.py is working for you, JSergio and Gujal00, then please ignore my post.

Thank you.

**Comment by bjgood** [comment]
Hey JSergio,
This is working for me...

from __resolve_generic__ import ResolveGeneric


class OnlyStreamResolver(ResolveGeneric):
    name = 'onlystream'
    domains = ['onlystream.tv']
    pattern = r'(?://|\.)(onlystream\.tv)/(?:e/)?([0-9a-zA-Z-_/]+)'

    def get_url(self, host, media_id):
        return self._default_get_url(host, media_id, template='https://{host}/e/{media_id}')

**Pull request merged**
